service: urfaviskpop

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs14.x
  stage: prd
  region: us-east-2

functions:
  bot:
    handler: src/lambda/handler.bot
    events:
     - schedule: rate(1 hour)
